name: Bug Report
description: Report a bug to help us improve
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the details below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: "Describe the bug here..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `suresign ...`
        2. Input ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen
      placeholder: "Expected behavior here..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Actual behavior here..."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS and version?
      placeholder: "e.g., Windows 11, Ubuntu 22.04, macOS 13.0"
    validations:
      required: true

  - type: input
    id: rust_version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "e.g., rustc 1.70.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Paste any error messages or logs
      placeholder: "Error output here..."
      render: text
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or information
      placeholder: "Additional details here..."
    validations:
      required: false
