name: Feature Request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature
      placeholder: "Describe the feature you'd like to see..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful?
      placeholder: "Explain the use case and benefits..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "Describe how you envision this feature working..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any other approaches?
      placeholder: "Describe alternative approaches you've considered..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "Additional details, screenshots, examples..."
    validations:
      required: false

  - type: checkboxes
    id: agree
    attributes:
      label: Acknowledgment
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature would be useful for others
          required: false
